- city: Aarhus
  latitude: 56.1572
  longitude: 10.2107

- city: Kongsvinger
  latitude: 60.1909
  longitude: 11.9987

- city: Nuuk
  latitude: 64.1835
  longitude: 51.7216

- city: Uummannaq
  latitude: 70.6744
  longitude: 52.1255
